### PR TITLE
add: One quarry sample

### PR DESCRIPTION
**Pull request by coumbsek**
Where a lot of vertical cliffs (benches) were classified as building

### CODE REVIEW

**Comment by pierotofy** [comment]
Hey @coumbsek :wave: thanks for the PR! We can't merge this as-is. Make sure to use the correct LAS ASPRS codes when classifying the point cloud? See the README for instructions.

**Comment by coumbsek** [comment]
Hi,
The dataset is a cloud generated by ODM that I edit, as per the recommandations. I change some 6 to 2 but it's the only edit I made. So there are points with 1, 2 and 3. 
- Does the sentence "At a minimum, the point cloud should have the following classification codes:" means that a dataset that lack one of this element can not be used as part of the training ?
- Or was the PR reject because (I just realized) there is a drilling machine wrongly classified as 2 instead of 64 ?

**Comment by pierotofy** [comment]
The classification codes of the contributed file are in the range 33-35 (which do not match the required codes).

image

Maybe it's a problem with the export in CloudCompare, does it work if the file is exported in LAZ 1.4 instead of 1.2? (If that's the case, we need to update the README).

**Comment by pierotofy** [comment]
Also, sorry for all the confusion! We're still ironing out the quirks of the contribution process :pray:

**Comment by coumbsek** [comment]
That is really really strange. I was not sure so I re-download the file from github to be sure. 
I check with CloudCompare and have the good values... BUT then I realised that I re-install it juste before to get rid off my alpha version (after reading the instructions on the repo) just to re-install another alpha version... I am dumb :(
With the stable release I have the same values as you. 
I will change all the values and re-upload it later (next week I think).

Don't worry it's how things progress, we are paving the way for the next, one stone at a time

**Pull request closed without merging**
